"""Ajout de date_retour_effective

Revision ID: d2a46ed61f4c
Revises: 
Create Date: 2025-09-25 13:06:19.160435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a46ed61f4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_retour_effective', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.drop_column('date_retour_effective')

    # ### end Alembic commands ###
